name: build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'out/**'
      - 'Dockerfile'
      - '.github/workflows/build.yml'
  workflow_dispatch:

env:
  TEST_TAG: vojkovic/searxng:test
  LATEST_TAG: vojkovic/searxng:latest
  GITHUB_LATEST_TAG: ghcr.io/privau/searxng:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vojkovic
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test Main Image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: ./
          file: ./Dockerfile
          tags: ${{ env.TEST_TAG }}

      - name: Test Main Image
        run: |
          docker run -d -p 8080:8080 -e AUTHORIZED_API=test_api_key ${{ env.TEST_TAG }}
          sleep 5 # Give the container some time to start
          curl http://localhost:8080/healthz > input.txt
          cat input.txt
          grep "OK" input.txt
          curl http://localhost:8080/search?q=github > input.txt
          cat input.txt
          grep "sidebar-end-collapsible" input.txt
          curl -H "Authorization: Basic $(echo -n "user:test_api_key" | base64)" http://localhost:8080/search\?q\=github\&format\=json > input.txt
          cat input.txt
          grep "number_of_results" input.txt
          
          docker rm -f $(docker ps -q --filter ancestor=${{ env.TEST_TAG }}) # Stop the container

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.LATEST_TAG }}
            ${{ env.GITHUB_LATEST_TAG }}
